### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Market#1]
_From @zvili on November 16, 2016 17:56_

_Copied from original issue: TechnionYP5777/SmartCity-ParkingManagement-A#1_

**Comment by zvili** [comment]
- Please define a Telegram group
- Send us your chosen users in Telegram
- Choose a group leader and share with us her/his user name.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement-B#2

**Comment by AviadCo** [comment]
Hi,
we opened a telegram group, what's your user name, i will add you...

**Comment by yossigil** [comment]
@AviadCo: Tag your partners.

**Comment by AviadCo** [comment]
Here are my partners: @shimonAzulay @LiorBenAmi 
need to add to the project: @noamyft,  @IdanAtias

**Comment by yossigil** [comment]
:+1:

**Comment by zvili** [comment]
@listopad

On Nov 17, 2016 22:06, Aviad Cohen notifications@github.com wrote:

Hi,
we opened a telegram group, what's your user name, i will add you...

**Comment by zvili** [comment]
Partners added.

**Comment by AviadCo** [comment]
@zvili here is a link for joining the group:

https://telegram.me/joinchat/DyIZLQmq8a3EcjjGZQIt1Q
