### ISSUE TITLE
Unit test for private methods

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#104]
Hi @yossigil ,

I'm dealing with a known problem: unit testing in java - private methods.
I've read over in the internet about ways to deal with the problem.
i also read this article:

http://www.artima.com/suiterunner/privateP.html

Here is a summary of the solutions which are mentioned there:

1. Don't unit test private methods - unacceptable by us.

2. Use wrappers to private methods in the tested class - unacceptable by us.

3. Use reflcation - this will take us too much time to test with and to use mocking with it.

4. Use "package" methods (the default of java) and put the test units in the same package of the tested class - we think it's the best option (need to o some code refactoring by still it's the best option).

We need your opinion here - do you know better way to deal with the problem? if not, does the way we chose is good enough?

Currently, i am refactoring the code and use the 4th option.

Thanks & Happy Hannuka,
Aviad Cohen

**Comment by AviadCo** [comment]
@shimonAzulay @noamyft @LiorBenAmi @IdanAtias Follow this issue

**Comment by shimonAzulay** [comment]
@AviadCo  I think that you shouldn't do unit test for private methods.
Private methods created for dividing your flow to logical parts called from the public methods. So when you will test your public methods (expose functionality) you will test your private methods as well.

**Comment by AviadCo** [comment]
I think you are right (after reading more and more)....
i will refactor the code to make it easier for testability.

10x

**Comment by yossigil** [comment]
IMHO, change all methods to package level.  It is rare that privacy against fellow package members is useful
