### ISSUE TITLE
Add persistence service to our project

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#123]

**Comment by IdanAtias** [comment]
what does it mean Hamadia?

**Comment by shimonAzulay** [comment]
@IdanAtias  Haha Hamadia ! For example, in the login screen you typed several passwords and usernames, and then close it and suppose the text fields are with history. So the next time we open that login screen we want to insert the data again. We need to save it in XML file and load the data from it. This is mainly for the GUI. 
Dear team @AviadCo @noamyft @LiorBenAmi  
Do you think this issue should be in the next semester ?

**Comment by AviadCo** [comment]
@shimonAzulay @IdanAtias I think it is a nice to have feature for now, and good feature for next semester.

**Comment by shimonAzulay** [comment]
@AviadCo  Do we have milestone for the next semester ? 
i will change the milestone

**Comment by AviadCo** [comment]
@shimonAzulay no, need to create one...

**Comment by shimonAzulay** [comment]
Hey guys @IdanAtias @AviadCo @noamyft @LiorBenAmi @TomPalny 
So i wondering what do you think about this issue?

**Comment by shimonAzulay** [comment]
We decided that this feature is necessary so i will add it to the project and write WIKI on it.

**Comment by TomPalny** [comment]
Definitely a good idea

**Comment by shimonAzulay** [comment]
Added WIKI : https://github.com/TechnionYP5777/SmartCity-Market/wiki/Persistence 
Added implementation to project.
Done.
