### ISSUE TITLE
smart-codes will be placed on all products and will able costumers and workers to get info on the product

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#13]

**Comment by yossigil** [comment]
I am not sure how this is an issue. When would it be closed/finished?

**Comment by IdanAtias** [comment]
Originally this was a US. 
We converted some of the USs we wrote into issues.
Is this more suitable as a US?

(This is true also for #14 #19 #20 )

**Comment by yossigil** [comment]
The whole story of user stories is undecied yet... But, an issue should be something dynamic that allows following progress. I think it would have been more appropriate to have issues with these titles

- Define groups of user stories.
- Create user stories / use cases for subtopic A.
- Create user stories / use cases for subtopic B.
- Generate class design as per user stories.


Cheers,

Yg.

@zvili @idabran

**Comment by IdanAtias** [comment]
Will do.

**Comment by yossigil** [comment]
You do not have to do this now, just because I said so. Only do this now, if it is important for **future** work. Otherwise, this is a lesson we learned. No need to cleanse the past.

**Comment by IdanAtias** [comment]
Got it, Tnx.
