### ISSUE TITLE
what is SM_SENDER_ID_DOES_NOT_EXIST error?

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#133]
I saw the error type SM_SENDER_ID_DOES_NOT_EXIST in the command descriptor, but i didn't find it in the result descriptor.
when to report this kind of error, and what is the difference between it and the SM_SENDER_IS_NOT_CONNECTED error?

**Comment by AviadCo** [comment]
The result 'SM_SENDER_ID_DOES_NOT_EXIST' is typo and should be written there 'SM_INVALID_SENDER_ID'. Maybe we don't need 'SM_INVALID_SENDER_ID' and 'SM_SENDER_IS_NOT_CONNECTED' since they are more or less the same. please use only 'SM_INVALID_SENDER_ID' when sender ID dosen't exist in the SQL server and we will remove 'SM_SENDER_IS_NOT_CONNECTED '

**Comment by AviadCo** [comment]
@noamyft  @LiorBenAmi  @shimonAzulay @IdanAtias 

Everyone agree?

**Comment by IdanAtias** [comment]
My first intention by defining SM_SENDER_ID_DOES_NOT_EXIST was to handle a situation when a client somehow needs to resume it's shopping and retrieve it's "old" shopping list from the server.
In case no such list exists under this sender id, we get this descriptor.
Maybe the other descriptors you mentioned can describe this as well....

**Comment by noamyft** [comment]
1. In the SQL class we have 2 exceptions for handling not valid Id: WorkerNotConnected and CartNotConnected. I hope this is fine.
2. @IdanAtias the case you mentioned is good, but i think we need better name for that.
What about: SM_LIST_NOT_EXIST_FOR_RECOVERY?

**Comment by IdanAtias** [comment]
sounds good

**Comment by AviadCo** [comment]
@noamyft @IdanAtias I removed 'SM_SENDER_ID_DOES_NOT_EXIST'.

In the future we will add 'SM_LIST_NOT_EXIST_FOR_RECOVERY' (it's probably will be added only after sprint 2).
