### ISSUE TITLE
Add a base Exception class for our modules

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#134]
SMException is a base class that all our module-based-exceptions should inherit from. (like AEmployeeException)

This allows us a more generic way for catching & handling our exceptions.

**Comment by yossigil** [comment]
It is rare that one has to define his own exceptions. double check / discuss this design decision.

**Comment by IdanAtias** [comment]
will do.
@noamyft - as i understood from @AviadCo, there is a similar exception to AEmployeeException in the SQL module. Should it be OK if you let this exception also extend SMException (just for consistency)?
