### ISSUE TITLE
Add a base-class-handler for handling exceptions in our GUI

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#135]
* GuiExceptionHandler is our generic way for dealing with exceptions that are caught in GUI level.
 * Each module we have that interacts with the GUI should inherit & implement this handler. (for example: Employee module should have EmployeeGuiExceptionHandler )

**Comment by yossigil** [comment]
In the mythical era that I will have time, we need to discuss exceptions.

**Comment by IdanAtias** [comment]
that could help...
