### ISSUE TITLE
Add new Worker unit test

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#143]
Due to Worker class expansion, need to write some new unit tests for methods:
- [x]  addProductToWarehouse 
- [x]  placeProductPackageOnShelves
- [x]  removeProductPackageFromStore
- [x] getProductPackageAmount

* open new issue for each one of them.

**Comment by AviadCo** [comment]
@Lior please choose on of the issues and close the second one (since they are both the same issue):

Create unit test for Worker implementation #81

**Comment by LiorBenAmi** [comment]
Done
