### ISSUE TITLE
Window size doesn't stay the same while moving between screens

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#169]
"new" window/screen should be the at the same size as the "old" window

**Comment by IdanAtias** [comment]
So I've managed to do some kind of a workaround to the problem by adding listeners to the window's size.
But there are still some side effects need to be taken care of. For example, lets say the current size of the window is X, and a dialog pop-up is shown. After closing the dialog pop-up, the window is resized to size Y and then back to X - it happens relatively fast but still noticeable. You can play with it a bit to see what I mean...
Anyway it seems like this is (or similar to) a known problem for ubuntu users : http://stackoverflow.com/questions/33134791/javafx-stage-cant-be-resized-after-showing-a-dialog

Maybe this won't happen in windows environment...

Anyway, if the current status is OK with us, we'll leave it this way and close this bug.
@shimonAzulay @LiorBenAmi @AviadCo @noamyft

**Comment by AviadCo** [comment]
@noamyft can you test it on the tablet? that's the only place we gonna run the client on.

**Comment by IdanAtias** [comment]
@noamyft if it is not OK on the tablet platform, reopen this bug.
