### ISSUE TITLE
Discuss how to deal with ProductPackage

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#176]
worke can:
* `addProductToWarehouse(ProductPackage p)`
* `placeProductPackageOnShelves(ProductPackage p)`
* `removeProductPackageFromStore(ProductPackage p)`
* `getProductPackageAmount(ProductPackage p)`

The valid data should be on the server.
Is it logic to send `ProductPackage p` to the server (not at creation)? Maybe need to hold ProductPackage Table in DB with unique key?
Need some more thought here..

**Comment by AviadCo** [comment]
We send ProductPackage on those commands since we don't want to create new structure for the key of ProductPackage (which is valid SmartCode + Location).

We thought about it and decided about the current API Commands.
