### ISSUE TITLE
Manager unit tests

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#183]
Unit tests for methods:
- [x]  addProductToCatalog 
- [x]  removeProductFromCatalog
- [x]  editProductFromCatalog

* open new issue for each one of them.

**Comment by yossigil** [comment]
My hunch is that issue per test method is too fine  a granularity

**Comment by LiorBenAmi** [comment]
@yossigil each method of these class gets it's own unit test file.
But I can aggregate the commits to reference only these main issue

**Comment by LiorBenAmi** [comment]
Done
