### ISSUE TITLE
The Cart Module - client

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#185]
## This is the main issue for the cart design and develop

The cart module represents a shopping cart in the SmartMarket.
It's main functions deal with the shopping experience of the SmartMarket costumer.
Costumer can add/remove products to/from the cart, and pays the bill in the end of the shopping.
To implement those functions the cart should: integrate with the server and DB, posses it's own data, and presents gui screens for user experience.

### General TODOs
- [x] **Logical design and implementation:** data structures, methods, contracts, exceptions...
- [x] **Client-Server communication:** commands descriptor, results descriptor, exceptions...
- [x] **Gui**

* Consider write wiki..

**Comment by shimonAzulay** [comment]
Nice 🤘

**Comment by LiorBenAmi** [comment]
Done. newer issues are live
