### ISSUE TITLE
change Command VIEW_PRODUCT_FROM_CATALOG -  server side

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#188]
Instead of creating new command, change this one to accept also not null expiration date.
The cart use this command too, with valid smart code
@AviadCo  @noamyft

**Comment by noamyft** [comment]
You can send Smartcode with expiration date - the server will ignore this field.
You can mention in the command descriptor that the exprition date is ingored and therefore can be null.
@AviadCo It is ok with you?

**Comment by AviadCo** [comment]
I agree - the server will ignore this field.
If you send null in expiration date it will be easier to debug if the server will wrongly try to access this field. (so it's better to send null). Anyway, whatever you choose the server should know how to deal with it.

@LiorBenAmi please close this issue if you agree...

**Comment by LiorBenAmi** [comment]
tnx. Agree
