### ISSUE TITLE
Employee GUI enhancement

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#189]
- [x] improve visibility of text in login screen
- [x] correct "forgot password string" in login screen
- [x] discard "login as worker/manger"
- [x] unite tabs in worker menu screens
- [x] improve visibilty of worker menu screen
- [x] add place for showing the current product detatils
- [x] add "success log" in the bottom of the worker menu window
- [x] add preloader 
- [x] When login - manage or worker
- [x] Barcdoe text fields support only digits
- [x] Date in datepicker cant choose if its older than current 
- [x] Enter key in the login screen 
- [x] Spinner in manage packages should disable the run operation button if changed
- [x] Search code disable when no code entered
- [x] Enter only digits in manage catalog product screen barcode

@shimonAzulay @LiorBenAmi @noamyft @AviadCo 
Work according to: https://s24.postimg.org/v6xj37ygl/photo_2017_01_06_03_13_05.jpg
and: https://s24.postimg.org/6h2mrfjyb/photo_2017_01_06_03_13_11.jpg

Add here more if needed...

#28

**Comment by AviadCo** [comment]
@IdanAtias Fine by me...
