### ISSUE TITLE
Integrate a coverage tool for our project in GitHub

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#190]
Currently investigating what's the best tool for doing this on github.

After integrated, this will give us useful info on how much of our code is covered and checked.

**Comment by yossigil** [comment]
Nice challenge!

**Comment by IdanAtias** [comment]
Can you plz grant access to "[Codecov](https://codecov.io/)" ? @yossigil @idabran @zvili 
It is a coverage tool (free for public repositories) that needs access to TechnionYP5777 in order to complete the integration.

**Comment by IdanAtias** [comment]
Done. +Added [Wiki ](https://github.com/TechnionYP5777/SmartCity-Market/wiki/Integrating-Codecov-with-a-GitHub-project-(Coverage-tool))& [badges ](https://github.com/TechnionYP5777/SmartCity-Market/blob/master/README.md)for "build" and "coverage".

@TechnionYP5777/smartcity-market  @tzjpgit
