### ISSUE TITLE
Cart - design cart gui screens

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#194]
General view of cart app UX, an main methods.
Do it before  continue implement logic

**Comment by LiorBenAmi** [comment]
@AviadCo @noamyft  @IdanAtias  @shimonAzulay  Hi guys, please check the cart screens design and share your opinions. Those are the main screens for the main methods of the cart app. Waiting for your comments in order to proceed to the implementation.
[Cart Screens (drive link)](https://docs.google.com/presentation/d/1v56A_QwRbth5mnLvINMX3AdPc-6BQr3dw_3BcEAWTtw/edit#slide=id.p3)

**Comment by AviadCo** [comment]
@LiorBenAmi I asked for access to this drive link

**Comment by LiorBenAmi** [comment]
tnx @AviadCo , please try [this](https://docs.google.com/presentation/d/1v56A_QwRbth5mnLvINMX3AdPc-6BQr3dw_3BcEAWTtw/edit?usp=sharing)

**Comment by LiorBenAmi** [comment]
Done

**Comment by LiorBenAmi** [comment]
#208
