### ISSUE TITLE
check possibility of abstract client

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#211]
abstract client that will contains both employee and cart common definitions and implementations:
* client defs
* AClient

**Comment by IdanAtias** [comment]
you want to create something like a base class for similar things that are used by cart & employee?

**Comment by LiorBenAmi** [comment]
yes, or actually classes. there some similar code

**Comment by LiorBenAmi** [comment]
moved to next sprint

**Comment by AviadCo** [comment]
no time for it... closing it..
