### ISSUE TITLE
Buying multiple items in Cart - allowed?

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#212]
@LiorBenAmi @noamyft @IdanAtias @shimonAzulay @idabran 

As you might all remember, we had discussion regarding this issue:
"Should we allow the cart user to add multiple item in the same transaction (e.g. buying 4 Milk Carton when scan only one)?" 

This might cause inconsistency - since the client might not check that he took 4 Milk with same smartcode (the same date) but told the cart he took 4 of the same item. On the other hand, not many users will add 10 bambas by scanning the all.

We didn't come up with decition for that issue.

Yesterday (10/1/17) i spoke with Itai and he suggested that we would allow to add multiple items in the same transaction, but will alert the user (a popup) that he should check that all the items he took were with the same smartcode.

Is that agreed by all? @LiorBenAmi - Can you this to the cart gui?

10x.

**Comment by IdanAtias** [comment]
Yea, but in this case it is still up to the user to decide if to obey this rule or not.
Consistency of our data maybe harmed this way.
AT THE MOMENT, I think we should avoid improving the usability on top of our data correctness.

Anyway, if the staff says otherwise, we'll go with them...

**Comment by AviadCo** [comment]
After the meeting we had last thusday, i think you are right and the for us now is to stay on the safe side of consistency, meaning allowing the the user to add/remove 1 item only when scanning it's specific barcode,

All agree here? @IdanAtias @LiorBenAmi @noamyft @shimonAzulay

**Comment by LiorBenAmi** [comment]
fix
