### ISSUE TITLE
Investigate how to handle the communication between client side and server side in java

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#22]

**Comment by IdanAtias** [comment]
as to how these 2 sides "talk" I think we can use JSON:
When transmitting a command from client to server (and vice versa) we can use json libraries in Java for converting the data we want to transfer to json format at the sender side and make it an object at the receiver side.

See more here:
http://www.devx.com/Java/Article/42399
http://stackoverflow.com/questions/32449369/json-data-from-client-side-to-object-on-server

**Comment by shimonAzulay** [comment]
My commit about this issue is mistake - the issue relevant to this commit is #26
