### ISSUE TITLE
Add isLoggedIn method for worker

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#220]
(This issue is derived from bug #219)

Should add a method for checking if worker is logged in: (something like worker.isLoggedIn() )
- [x] add command api
- [x] add implementation in client side
- [x] add implementation in server
- [x] add support in SQL

@noamyft @AviadCo

**Comment by noamyft** [comment]
What are the parameters: username or sessionID?

**Comment by noamyft** [comment]
I added 2 methods:
1) Using username of worker (only!) to check status
2) Using session id of worker or cart to check status

(Not implemented yet)

**Comment by AviadCo** [comment]
@IdanAtias @shimonAzulay 

Command infrastructure is ready, you can add integration with the Employee GUI.

**Comment by IdanAtias** [comment]
Great. will do!
