### ISSUE TITLE
Investigate how to implement server

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#23]

**Comment by IdanAtias** [comment]
have a look at #22

**Comment by shimonAzulay** [comment]
Guys i added some high level questions for the server side. feel free to change it, issue it or add some more.
1. How to handle parallel requests from clients.
2. How to handle the communication between client and server.
3. Which SQL implementation is the most suitable for our use.
4. What SQL tables should we create and what should each of them will contain.
5. How should we handle containers with SQL (for example: request an element from a container stored in    SQL database - should we parse all the container into Java and then look for the element or should we only get the requested element parsed to Java)

**Comment by yossigil** [comment]
You must run a search for existing servers in Java, and write a wike page describing your discoveries.

**Comment by yossigil** [comment]
This issue is  half vague hal vacuous. There is no telling when it would end, what's achieved in it, etc. But, perhaps if the issue is closed (it has been open forr 9 days), we would see where it leads to.

**Comment by AviadCo** [comment]
The server side is divided to three logical parts:
1. Communication with clients (Carts, Worker, Manager).
2. Process requests.
3. Apply request by accessing the SQL database (and sometimes changing it's state).

The first logical part (communication with the clients) can be found here:
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Client-Server-Mechanism
