### ISSUE TITLE
cart bug - establishConnection when server is down throw unhandeled exception 

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#235]
Need to wrap that method call with try/catch clause - in all the methods that communicate with the server.

**Comment by LiorBenAmi** [comment]
@IdanAtias @shimonAzulay  maybe relevant to Employee methods too

**Comment by IdanAtias** [comment]
I believe it is on purpose because the exception we get there is RuntimeException and actually marks that server is not reachable....so the client software can't proceed.

BUT, I do think we should re-think about it and maybe catch this exception and close the program gracefully.

**Comment by LiorBenAmi** [comment]
yeah but if you catch it inside your class method you can then throw your class declared exception like CriticalError... thats what I think I'm gonna do..

**Comment by IdanAtias** [comment]
so we need to find out what was the original intention by throwing RuntimeException.
I believe @AviadCo wrote the ClientRequestHandler so maybe he can help here

**Comment by AviadCo** [comment]
@LiorBenAmi @IdanAtias i fixed it by adding new exception to worker which is called 'ConnectionFailure', please view this issue and the commit fix i did for it in #243 because i think we should also fix it in the cart.
