### ISSUE TITLE
add method on Server to get manufacturers list

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#248]
(Derived from issue #140)

**Comment by AviadCo** [comment]
@noamyft  What am i supposed to do here?

**Comment by noamyft** [comment]
To add the relevant command on the server
The method exist in the SQL, just call it and return the answer
(The result is pairs of (manufacturer id, manufacturer) in Hashset<Integer,Manufacturer>)

**Comment by AviadCo** [comment]
I think it's good idea for next semester, do you agree @noamyft ?

**Comment by noamyft** [comment]
Yes
