### ISSUE TITLE
When existing using X when the client is still logged on, an exception is thrown

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#249]
@IdanAtias can you take a look at that? this exception is was thrown even before my change.
Moreover - can you please check that i remove the workaround when adding the ConnectionFailure exception?

**Comment by shimonAzulay** [comment]
@IdanAtias  @AviadCo  
This exception is throwing no matter if the server is up or down, please check this exception in normal flow.

**Comment by IdanAtias** [comment]
fixed
