### ISSUE TITLE
ProductPackage parameter in Manager methods 

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#250]
The manager methods should get ProductCatalog and not ProductPackage as parameter.
please fix the interface and the implementation. In the server side its seems to look OK.

please check the manager unit tests, there are some mistakes there, with this issue and the command descriptor that we are sending there ( right now using ADD PRODUCT TO WAREHOUSE -> should use ADD PRODUCT CATALOG)

P.S consider to send to Remove catalog product method only barcode.

Thanks.

**Comment by AviadCo** [comment]
@shimonAzulay Great job for finding this mess, please contact me for more logic bugs
