### ISSUE TITLE
modify CartProduct and Cart Classes

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#255]
In order to support right flow in cart gui, need to change 
* CartProduct Class: from {CatalogProduct cp, DateTime expiration, int amount} to {CatalogProduct cp, HashMap<SmartCode, ProductPackage> packages, int totalAmount}. In this way we can present the products in the cart and let the user update them in the right way.

* Cart Class: cartProductCache changed to HashMap<Long, CartProduct> : Key: barcode, Value: CartProduct

TODO:
- [x] implement classes
- [ ] unit test

**Comment by AviadCo** [comment]
@noamyft can you have a look at this?

**Comment by LiorBenAmi** [comment]
basic QA done. unit test next sprint
