### ISSUE TITLE
Design & Create Worker + Manager Class

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#26]
1. Use heritance between Manager and Worker (Since Manager IS-A Worker).
2. Create the classes infrastructure - private attributes, get/set methods, simple operations.

**Comment by shimonAzulay** [comment]
Made a commit about this issue, unfortunately inserted wrong issue number in my commit.
The commit id about this issue is - 
1ba888026aae68200186d28504870530c4f648d8

This issue is still on going though its not closed.

**Comment by yossigil** [comment]
Good recovery @AviadCo

**Comment by yossigil** [comment]
When do you expect this issue to close?

**Comment by IdanAtias** [comment]
design & creation of this class is pretty much done.
the class's logic is already written both in client and server sides.
What's left is continue developing the worker GUI, thus, i believe this can be closed.
@AviadCo @shimonAzulay correct me if i'm wrong. (and if i am - reopen this)

**Comment by AviadCo** [comment]
@IdanAtias I agree.
