### ISSUE TITLE
bug in Command: CHECKOUT_GROCERY_LIST

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#264]
when using it with new cart and empty grocery list I get - SM_OK while I should get SM_GROCERY_LIST_IS_EMPTY.

**Comment by AviadCo** [comment]
I check and you are right, currently the server dosen't support this result, will be added in next sprint

**Comment by AviadCo** [comment]
@noamyft can you add support to this result in CommandExectuer & in the sql?
