### ISSUE TITLE
Design & Create SmartCode & Product Classes

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#27]
Create the classes infrastructure - private attributes, get/set methods, simple operations.

**Comment by LiorBenAmi** [comment]
First Design will be upload to an informative wiki page.
Also, the code will be commited in until weekend (10.12)

**Comment by noamyft** [comment]
@LiorBenAmi 
I edited your comment (added date)

**Comment by yossigil** [comment]
I hope @LiorBenAmi  knows what to do here. This is one vague issue. Please correct.

**Comment by LiorBenAmi** [comment]
@yossigil the issue was about creating the basic classes we agreed on for the project infrastructure - we presented them here: #40 

Done
