### ISSUE TITLE
Display error while scanning not existed barcode

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#277]
When the manager scan not existed barcode and he is on Add Product To Catalog tab - its dixplay error

**Comment by AviadCo** [comment]
There is an error message, @noamyft can you please check again?

**Comment by shimonAzulay** [comment]
Hi @noamyft can you please clarify the scenario of the bug, i couldn't understand it so well.

**Comment by AviadCo** [comment]
This bug doesn't happen anymore, closing issue....
