### ISSUE TITLE
Fix total items in cart

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#280]
The total item in cart should be the total amount and not total rows

**Comment by LiorBenAmi** [comment]
it's not a bug it's a feature. Currently this field presents the number of the different product in cart (distinguish by barcodes) in purpuse. I agree it's confusing, but I still want to present it. I'll think of away to make it more clear and add total items as you assigned also.

**Comment by LiorBenAmi** [comment]
made little change in cart data (to avoid time complexity).. Fixed
