### ISSUE TITLE
Bug: The server remove the products in cart on cancel

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#282]
The server should return the purchased items to shelves when user cancels purchase.

**Comment by LiorBenAmi** [comment]
notice: cart cancel its not an unique implemented command client-server. cancel from cart gui side simply call to logout

**Comment by noamyft** [comment]
This bug fix cause another bug and "raised from the deads" internal bug from the HSQLDB library, so its took a lot of time to find and fix those bugs.
