### ISSUE TITLE
Team Meeting with Tom & Itai on Sunday 26.3

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#289]
Invited:

@idabran 
@TomPalny 
@shimonAzulay 
@noamyft 
@AviadC 
@LiorBenAmi 
@IdanAtias

**Comment by TomPalny** [comment]
Thanks, the meeting time will be 13:30

**Comment by shimonAzulay** [comment]
Good!

**Comment by shimonAzulay** [comment]
@TomPalny Hi after our meeting tomorrow , can we schedule our next meetings on Monday? 
@IdanAtias @AviadCo @noamyft @LiorBenAmi Could it work for you guys?

**Comment by TomPalny** [comment]
I'm fine with it. We'll talk about it tomorrow

בתודה,
תום

**Comment by AviadCo** [comment]
Summary meeting:

* Add Wiki pages: Coding standarts, Code coverage & testing (how and what is included in the tests), install me (what needs to be done to run project on eclipse), Milestones (what need to be done in each Milestone).

* Fix Git labels: Remove Critical, Nice to have, Usefull

* Assignments:

Noam - bug in Command: CHECKOUT_GROCERY_LIST #264
             Bug: The server remove the products in cart on cancel #282

Lior - Fix total items in cart #280
          Cart - unit tests #198
Idan - The GUI not fit to screen resolution #278

Shimon - The GUI not fit to screen resolution #278

Aviad - Display error while scanning not existed barcode #277

* Possible features to next milestone:

- Upgrade Cart to Customer.
add ability to login, save information, filter ingredients, cross out already bought items, discount items
Guest login: none of the above (similar to cart as it is now) 
- Fridge
- Persistent memory management
- Gui testing tools
- Using special gui animation libraries
- statistics

**Comment by AviadCo** [comment]
Create Wiki for Code coverage and testing #302
