### ISSUE TITLE
Implement Client-Side basic Connection with server

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#29]
Please read Wiki regarding this issue.

**Comment by AviadCo** [comment]
Assigned myself instead of Lior since it's better that the person which implement server side connection will implement the client side also.

**Comment by yossigil** [comment]
:+1:

**Comment by AviadCo** [comment]
[Commit related to issue.](https://github.com/TechnionYP5777/SmartCity-Market/commit/67b96e5bdb0bf22958dcb4d660276d395590a020)
