### ISSUE TITLE
Reduce Git labels

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#290]
No more than 10 labels.

**Comment by noamyft** [comment]
I suggest to create the following labels:
Bug
Critical
Useful
Nice to have
Administrations
Server side
Client Side
Manager
Employee
Cart/Costumer

@AviadCo @shimonAzulay @LiorBenAmi @IdanAtias 
contact me if you think otherwise.

**Comment by noamyft** [comment]
Instead of Useful, I renamed Useful/enhancement

**Comment by noamyft** [comment]
@TomPalny 
I rearrenged the lables, but I kept another 4 lables because we used them a lot.
also, Quality assurance and Teaching lables not related to us.
is this ok?

**Comment by TomPalny** [comment]
Quality assurance is a label I kept for the weekly log. We can think of a
better alternative if you wish

בתודה,
תום

**Comment by noamyft** [comment]
I think it's fine. I just wanted to be sure i can keep them, because you asked us to use up to 10 labels.

**Comment by noamyft** [comment]
Finally, we decided to remove Critical,Useful,Nice to have lables and move Client-Server Layout into Common
