### ISSUE TITLE
Karma and Todos for Idan Atias

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Market#3]
_From @IdanAtias on October 30, 2016 22:7_

- [x]  Make sure you present yourself by a readable nick
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job
- [x]  Connect to the host repo

_Copied from original issue: SpartanRefactoring/Spartanizer#659_

**Comment by zvili** [comment]
_From @IdanAtias on October 30, 2016 22:12_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @AviadCo on October 31, 2016 5:1_

Great Job my friend! you have good karma :+1: 
my karma is #528

**Comment by zvili** [comment]
_From @LiorBenAmi on November 8, 2016 22:13_

Good Karma dude! 💯 
these is mine : #772

**Comment by zvili** [comment]
_From @yossigil on November 9, 2016 9:0_

 Labels? Deadeline?  Who is the assignee? 
Karma -= 10

**Comment by zvili** [comment]
_From @yossigil on November 9, 2016 9:0_

@zvili @idabran @yh-github @AdiOmari @orimarco

**Comment by IdanAtias** [comment]
So far:
- Participated in team meetings for making assessments of project scale and functionality. #40
- Made an investigation about a client-server protocol which lead to choosing JSON as the "language" the server and client talk. #22 (see wiki [here](https://github.com/TechnionYP5777/SmartCity-Market/wiki/JSON-For-Client-Server-Data-Exchange))
- Made an investigation about the use of java libraries that can handle databases. #34 #25 (see [this ](https://github.com/TechnionYP5777/SmartCity-Market/wiki/Java-APIs-for-handling-databases)wiki)
- Was part of converting and expanding our projects USs to corresponding issues. 
   (see #13 #14 #15 #16 #17 #18 #19 #20 #21)
- Suggested we use [ZenHub ](https://www.zenhub.com/)as chrome extension for better use of GitHub functionalities. #49 
- Was (and still is) part of planning & implementing the "Manager/Worker" classes and GUI. #10 (see #26 #28)

@yossigil @zvili @idabran

**Comment by yossigil** [comment]
Please clean the above, mentioning only issues you closed, or did some observable work on. If you did some work without issues documenting you may in some cases create the issues retroactively, in some cases though, this is impossible.

**Comment by IdanAtias** [comment]
Tnx, good to know. I've now attached an issue id to some of them. I will retroactively open (and close) new issues that refers to the rest of things I mentioned and currently have no issue id attached.

**Comment by yossigil** [comment]
Edited this for you.
