### ISSUE TITLE
Create Wiki for Code coverage and testing

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#302]

**Comment by AviadCo** [comment]
@noamyft @shimonAzulay @LiorBenAmi @IdanAtias 
Finished, please view and edit if needed:
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Testing-&-Code-Coverage

**Comment by TomPalny** [comment]
Hi Aviad, the "Testing" wiki, in addition to what you wrote, needs to have **_instructions_** for a user from outside on how to test the code, what command to write in the terminal, something that will give an input indicating if the project is healthy or not. 
This is the first thing you need to write in this wiki.

**Comment by AviadCo** [comment]
@TomPalny Ack. 
I updated the WIKI:
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Testing-&-Code-Coverage
Can you please check again?
