### ISSUE TITLE
Create Coding Standart wiki page

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#303]

**Comment by LiorBenAmi** [comment]
Done.
[wiki page](https://github.com/TechnionYP5777/SmartCity-Market/wiki/Coding-Standard)

**Comment by noamyft** [comment]
I want to modify the spartanizer (remove dollars, cents, etc..)

**Comment by noamyft** [comment]
I added the necessary changes.
