### ISSUE TITLE
Implement SQL Database and server SQL interface

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#31]
Please read the Wiki regarding this issue:
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Java-APIs-for-handling-databases

1. Start with implementing SQL Database (table and infrastructure).
2. Design and implement the interface for working with the SQL.

**Comment by noamyft** [comment]
We decided to use JDBC, and use local SQL database.
I first investigating how to implement local SQL database.

**Comment by yossigil** [comment]
:+1:

**Comment by noamyft** [comment]
After lots of digging, I will use the HSQLDB (HyperSQL Database) embeddable database for the SQL database.
I will write Wiki about it and how to use it.

**Comment by yossigil** [comment]
I was not convinced you work at the right pace.... @zvili @idabran

**Comment by IdanAtias** [comment]
@noamyft 
Regarding your commit - no need to add the gson dependency to Server module or any other module specifically.
I already added it to the the enitre project.
Can you revert those lines? (then you can do SmartMarket-->Maven-->Update project and you should have the gson still "working". just be rebased.)

**Comment by noamyft** [comment]
@IdanAtias I fixed the dependency - it's work! 
(It didn't work last week... weird..)
