### ISSUE TITLE
Applying Coding Standard into your code

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#322]
Please read the wiki about Coding Standard. apply the standards to your code and handle the warning from eclipse and tips from the spartanizer.
Please check your progress:

Aviad:
- [x] apply Coding Standard.

- [x] handle warnings and tips

Noam:
- [x] apply Coding Standard.

- [x] handle warnings and tips

Shimon:
- [x] apply Coding Standard.

- [x] handle warnings and tips

Lior:
- [x] apply Coding Standard.

- [x] handle warnings and tips

Idan:
- [x] apply Coding Standard.

- [x] handle warnings and tips

**Comment by AviadCo** [comment]
@noamyft i fixed most of the compiler warnings:

Fix many compiler warnings #326

it's a little bit annoying to use:

empty statement
unused object allocation

1. We get warning for good code in testing and right functionality code, i think it's better to remove those.

**Comment by IdanAtias** [comment]
As @AviadCo already said, "empty statement" & "unused object allocation" are causing warnings in our project.
Lets decide and update the wiki accordingly.

**Comment by noamyft** [comment]
- "empty statement" is rarely happened for good reason. the specific cases that used it for good reason (like in class ClientServerCommunicationTest) will annotates with @suppressWarnings

- about "unused object allocation" - i remove this warning from the list. do it too

**Comment by AviadCo** [comment]
@LiorBenAmi Can you fix you part and close this issue?
