### ISSUE TITLE
Create Wiki for Client-Server implementation

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#33]
Please view the information from issue #22

**Comment by IdanAtias** [comment]
@AviadCo @shimonAzulay 
Already did this. You can close this issue.

P.S
You can add more data to this Wiki though...

**Comment by shimonAzulay** [comment]
@AviadCo closed

**Comment by yossigil** [comment]
Where is the wiki #6 ???

**Comment by shimonAzulay** [comment]
@yossigil  is that not ok ?
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Client-Server-Mechanism
