### ISSUE TITLE
Cart to Customer transition

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#332]
- [x] Refactor Cart class (phase 1 - names changing & refactor maven dependencies)
- [x] Refactor Cart class (phase 2 - more specific refactoring on Cart related classes, exceptions etc.)
- [x] Refactor Cart to Customer at Server (@AviadCo)
- [x] Refactor Cart to Customer on SQL (@noamyft)
- [x] Create CustomerProfile class #329 
- [x] Change login mechanism (using CustomerProfile) - Client side
- [x] Change login mechanism (using CustomerProfile) - SQL + Server side  (@noamyft)
- [x] Extend Customer to RegisteredCustomer
- [x] Define basic interface for RegisteredCustomer
- [x] RegisteredCustomer basic implementation (main functionalites)
- [x] Unit-testing for Customer module (see #378 )
- [x] Merge CartToCustomer branch to master branch

**Comment by IdanAtias** [comment]
Opening a new branch for doing the transition from Cart to Customer, when it's done and seems stable, we'll integrate it to master branch. @AviadCo @noamyft @LiorBenAmi @shimonAzulay

**Comment by IdanAtias** [comment]
For successfully making the transition in your eclipse environment, make a right click on the parent module "SmartCity-Market" --> Configure --> Configure and detect...

Then you should see a highlighted line with the word Customer, make sure it's marked with V and press Finish/OK.

That's of course after doing "git fetch --> git checkout -b CartToCustomer origin/CartToCustomer"

If git "yells" about .ignore files or .project files, keep them in a tmp directory, do what git says, and if something is not working, restore these files.

Run "maven clean install" for making sure everything went fine. You should see something like this:
[https://ibb.co/nsp2Jv](https://ibb.co/nsp2Jv)


**Make sure to work on this issue just on the CartToCustomer branch in the meantime, till we are confident we can merge it to master***

**Comment by yossigil** [comment]
:100:

**Comment by IdanAtias** [comment]
@AviadCo @noamyft 
Plz see above check-boxes and update accordingly...tnx

**Comment by AviadCo** [comment]
@noamyft regarding  Change login mechanism (using CustomerProfile) - SQL + Server side
After updating the SQL, please call your function from the CommandExecuter (you have TODO there)

**Comment by AviadCo** [comment]
@IdanAtias The check boxes which no one is mentioned at the end are yours?

**Comment by IdanAtias** [comment]
@AviadCo currently yes...

**Comment by LiorBenAmi** [comment]
@IdanAtias I'm still working on some bugs in Cart module. I don't merging for now cause I need the gui working fine. We will need to merge it carefully when we both done.

**Comment by IdanAtias** [comment]
@AviadCo @LiorBenAmi 
Merge is done.
Unit-testing and additional support for customer is still needed.

**Comment by IdanAtias** [comment]
@noamyft Plz close this issue if the relevant check-boxes for u are done or handled somewhere else.

**Comment by IdanAtias** [comment]
@noamyft - remind you...

**Comment by AviadCo** [comment]
@noamyft  - come on let's close this (fix the logins in the server.....)

**Comment by yossigil** [comment]
:+1:
