### ISSUE TITLE
Design high level implementation of the project

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#35]
Design high level classes and modules and the connections between them.

**Comment by yossigil** [comment]
It makes no sense to place a desing issue for five people.

**Comment by shimonAzulay** [comment]
@yossigil  we are in a meeting right now and we all work on the design.

**Comment by yossigil** [comment]
Please specify what the "design" should include. 
remember a prototype is also an option

**Comment by yossigil** [comment]
How come there is no assignee?

@idabran @zvili

**Comment by yossigil** [comment]
#6

**Comment by shimonAzulay** [comment]
Ok maybe we @AviadCo @IdanAtias  @LiorBenAmi  @noamyft  misunderstood. We wanted our meeting to be record. So this is why we open this issue and assign all our team. How should we record our meeting (with all the team) probably ?
@yossigil

**Comment by yossigil** [comment]
If this is a meeting, I suppose it is OK, even though it would make sense if the issue/wiki
- would be entitled "minutes of meeting at XXX", rather than "design"
- the person who recorded the minutes is the author or this issue.

**Comment by yossigil** [comment]
What's going on @shimonAzulay

**Comment by shimonAzulay** [comment]
Before i edit the issue and get more bad Karma i will ask...
Can you explain - would be entitled "minutes of meeting at XXX", rather than "design"
and second, if i will assign myself for this issue and close it after we will finish publish the design in the wiki page it will be alright?

**Comment by yossigil** [comment]
Search google for "minutes of a mintue"
I am confused. Is this a summary of a meeting, the deliverables are the minutes"
If this is a call for design, then it so vague and assigned to too many to be of any use, what's the deliverable? Who will do it?

**Comment by yossigil** [comment]
This isssue has not been touched for 14 days.

**Comment by shimonAzulay** [comment]
@yossigil Yes sorry for that, guess we were busy coding our project haha :)
I think we can close this issue due to #42
What do you think ?
