### ISSUE TITLE
Compile part of the project files

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#36]
Should we split the code to different projects holding the project modules and compile each of one of them or should we hold the all project modules in the same project.
Investigate if we can compile parts of the project files.

**Comment by yossigil** [comment]
Remember that you are to use maven

**Comment by yossigil** [comment]
#6 How come there is no milestone?

**Comment by shimonAzulay** [comment]
@yossigil fixed

**Comment by yossigil** [comment]
Which project files do you refer to?

**Comment by shimonAzulay** [comment]
It is from our design. we need to finish showing the design in the WIKI page and then i will edit this issue so it will be more clear, pointing the the "files" from the design. is it ok ? or there are more things that unclear ? @yossigil

**Comment by yossigil** [comment]
@idabran @zvili Can  you help Shimon write a clear issue with deliverables. If this issue is pending on something else, please mention this.

@shimonAzulay : do yo mean a prototype implementation?

**Comment by IdanAtias** [comment]
@shimonAzulay can we close this issue? I believe this discussion can me merged with #37 and #45

**Comment by shimonAzulay** [comment]
close due to issue that related to this issue - #45
