### ISSUE TITLE
Replace "Cart" username to "Guest"

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#362]
Need to declare class that contain the defs related to the communication between server and client and use those defs (instead of each side declare its own consts).

**Comment by noamyft** [comment]
@AviadCo please change the customer to use the Definitions in the ClientServerDefs (instead of hard-coded string "Guest")

**Comment by AviadCo** [comment]
@noamyft - Done, i closed this issue...
