### ISSUE TITLE
RegisteredCustomer need IS_FREE_CUSTOMER_NAME

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#373]
@AviadCo  @noamyft 
Hi, it is necessary to Customer Registration Screens to have these command in order to inform the user immediately when it enter in-used user name.

**Comment by AviadCo** [comment]
@LiorBenAmi 
Can you please open an issue which describes the full flow on the registration (including steps and which commands / checks should be by the Customer side and Server side)?

Thanks & Happy Passover

**Comment by LiorBenAmi** [comment]
@AviadCo

**Comment by AviadCo** [comment]
Hi,
@noamyft - connect the SQL to the command in the server side
@LiorBenAmi - connect the GUI to the logic in Customer side (and check that the full flow works)

**Comment by AviadCo** [comment]
done...
