### ISSUE TITLE
Platform for run the cart implementation 

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#38]
Investigate with Itay and Zvi about the Win10 OS tablets they offer us to use for the cart implementation:

You should take the tablet, investigate if you can run the cart application on it.
In the end you should post a conclusion if we can/cannot use it, and how.

**Comment by yossigil** [comment]
I do not think anyone can tell when this is done. So the issue is not well defined.

**Comment by noamyft** [comment]
I updated the issue and specified what should we do.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
Don't use labels instead of milestones. @noamyft : also correct for other issues with this label

**Comment by noamyft** [comment]
@yossigil 
When we need to use "sprint 2" label?

**Comment by yossigil** [comment]
@noamyft: as I said. There are labels, and there are milestones. Don't confuse them.


@zvili @idabran

**Comment by noamyft** [comment]
I took the phone yesterday (11.12), and now i look into it.
I will report my results soon (today or tomorrow).

**Comment by noamyft** [comment]
Unforunetly, i didn't find a formally way to run java on Windows 10 Mobile.
Read this:
http://stackoverflow.com/questions/34360696/java-on-windows-10-mobile

We need to decide what to do next. Maybe tablet?
 @zvili @idabran

**Comment by noamyft** [comment]
I will take the tablet for the cart from Zvi and Itai

**Comment by noamyft** [comment]
We will use the tablet, and we will build "external scanner" with android.

**Comment by yossigil** [comment]
💯
