### ISSUE TITLE
Add mechanism to fetch product pictures from server

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#380]
Currently, The clients side (Customer and Manager / Worker) fetch the product pictures from local storage.

In the long run, we need the clients to get pictures updates from the server.

Me, @IdanAtias & @noamyft designed a mechanism to implement this issue.

**The mechanism flow:**
On start of the application in the client size, the client send command with it's most updated files DATE. the server check whether it has new DATE for it's files and respond to the client.
If the server has newer pictures (newer files DATE), the client will send another command to ask for the new files and the server will send the client the updated files. The client side will maintain the current Date   of the files and remove the old files and update to the new ones.

**For this to be done, here are the issues we need to implement:**

@IdanAtias 
- [x] Design and add command API to implement this feature (For Customer & Employee)
- [x] Add common class which will pack / unpack files (we will send the picture as one packed file)
- [x] Add common class to send / receive files
- [x] Add support to the commands in Customer 
- [x] Add support to the commands in Employee
- [x] Move logic of UPDATE_PICTURE command to Common
- [x] Use PictureManager to fetch date of pictures (instead of LocalDate.MIN)
- [x] Handle to NO_NEED_TO_UPDATE result (instead of checking null) + update CommandDescriptor 
- [x] Write unit test for this mechanism at Customer module
- [x] Write unit test for this mechanism at Employee module

API

Me:
- [x] Add supports to the commands in server side
- [x] Add PictureManager class to handle the most updated pictures date

**Comment by IdanAtias** [comment]
I implemented encode/decode method for Packing module for allowing to encode the files we send to Strings and decode from String back to files, so we currently don't need to implement a different mechanism for transferring files. So I mark this checkbox as done and continue working on the rest.
If we run into problem we will re-think of it.
@AviadCo

**Comment by IdanAtias** [comment]
@AviadCo I also added the command API, plz review it and let me know if it's ok.

**Comment by AviadCo** [comment]
@IdanAtias i am on vacation this, i will design and implement the commands need here next week

**Comment by IdanAtias** [comment]
Done.
