### ISSUE TITLE
WIN 10 Tablets scanner

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#39]
#38
Check if we can use the tablets camera for smart code scanner.

**Comment by yossigil** [comment]
Take note that you cannot use windows in this project

**Comment by shimonAzulay** [comment]
@yossigil  @idabran @zvili @LiorBenAmi @IdanAtias @noamyft @AviadCo 
As discuses with Itay and Zvi - we wanted to use WIN10 tablets for the Cart implementation.

**Comment by LiorBenAmi** [comment]
#43
