### ISSUE TITLE
Remove stack trace prints and from all over the project

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-Market#390]
This means you only print stack traces in tests.
This code should not be there...
@TomPalny 

![image](https://cloud.githubusercontent.com/assets/12775400/25334500/75ad105a-28f7-11e7-9427-3e2a9e819446.png)

**Comment by AviadCo** [comment]
@yossigil @TomPalny 
As you can see, there is FATAL print to log in the catch close.
FATAL means something bad happens and need to debug. The print stack trace can give us more information to debug. (we use many prints to fully understand what happened in such case)

**Comment by yossigil** [comment]
sorry to be picking on his. but this means you won't be paying as much attention to the log as you may need to

**Comment by AviadCo** [comment]
Do you have a suggestion for improvement? (for now, when debuging we check the log files for FATAL and for stack trace and we find the source of the bug in less than 2 min.)

**Comment by yossigil** [comment]
just erase the printStackTrace.
All information should be retrieved from the log

**Comment by AviadCo** [comment]
O.K.
Changed issue to: Remove stack trace prints and from all over the project

**Comment by shimonAzulay** [comment]
Hi @AviadCo i will do it in the Employee module and in the packages i wrote in the common module

**Comment by yossigil** [comment]
:+1: @TomPalny
