### ISSUE TITLE
add support to FORCE_REMOVE_INGREDIENT

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#397]
this command should vanish given ingredient entirely form the system.
this method should be:

- [x] Defined in api

- [ ] implemented in SQL database.

- [x] used in client side logic

**Comment by AviadCo** [comment]
@noamyft when do we use it?

**Comment by AviadCo** [comment]
@noamyft please add SQL implementation
@shimonAzulay Please add this option to GUI in Employee side

**Comment by AviadCo** [comment]
@noamyft @shimonAzulay let's finish this issue...
