### ISSUE TITLE
Karma and Todos for Aviad Cohen

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Market#4]
_From @AviadCo on October 26, 2016 19:35_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#528_

**Comment by zvili** [comment]
_From @AviadCo on October 26, 2016 19:42_

@yossigil : Done.

**Comment by zvili** [comment]
_From @noamyft on October 26, 2016 20:9_

Good luck!! :100:

**Comment by zvili** [comment]
_From @nisanarz on October 27, 2016 12:34_

Great Karma page! ;)
Please check out mine #542

**Comment by zvili** [comment]
_From @zahimizrahi on October 28, 2016 6:52_

Keep up the good work! 

check out mine #551

**Comment by zvili** [comment]
_From @yossigil on October 28, 2016 7:15_

1. Keep this open
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
3. Assign yourself if you haven't done so yet.
:+1:

**Comment by zvili** [comment]
_From @AviadCo on October 29, 2016 20:12_

@yossigil : **PSB [AC]**
1. Keep this open
**[AC] done.**
2. Edit the content of the main issue, to remove the junk. Just leave the checked todos in it.
**[AC] done.**
3. Assign yourself if you haven't done so yet. 👍
**[AC] done.**

**Comment by zvili** [comment]
_From @yosefraisman on October 30, 2016 18:38_

Your karma page is so great, it's a Nobel prize in literature waiting to happen! please check out mine at #616

**Comment by zvili** [comment]
_From @yonzarecki on October 30, 2016 19:35_

Nice work !

**Comment by zvili** [comment]
_From @IdanAtias on October 30, 2016 22:19_

Nice work!
plz feedback me ;) #659

**Comment by AviadCo** [comment]
**Issue i worked on in Sprint 1:**

Sort user stories by priority #11
Fill project readme #46
Create WIKI to explain SmartCode definition #47
Design meeting summary #40
Create a WIKI about Client-Server communication #54

@zvili @idabran @yossigil

**Comment by yossigil** [comment]
Please clean the above, mentioning only issues you closed, or did some observable work on. If you did some work without issues documenting you may in some cases create the issues retroactively, in some cases though, this is impossible.

**Comment by AviadCo** [comment]
Done. @zvili @yossigil @idabran
