### ISSUE TITLE
Design meeting summary

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#40]
#35
System Diagram 
https://drive.google.com/open?id=0B4g5jbhEYGZxdXk1cmlQQ1d0UDQ

Classes description
https://drive.google.com/open?id=0B4g5jbhEYGZxTUN5WnRYRVdoTkU

Basic flow 
https://drive.google.com/open?id=0B4g5jbhEYGZxY3lPMkItOEM2bWM

**Comment by yossigil** [comment]
This is not "design" ..
A design is a wiki page.

No milestone, no lables. no assignees = BAD JOB.

**Comment by LiorBenAmi** [comment]
#27

**Comment by shimonAzulay** [comment]
@yossigil for the Milestone we added new ones and we have need to change it (we didn't forget it...)
for the lables we added Design - as this what we did.
for the assignees - again as said in #35 
About the WIKI page we will add a design there as well.

**Comment by LiorBenAmi** [comment]
opened- #42
therefore - Done
