### ISSUE TITLE
Implement encoder of SmartCode

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#41]
You should implement the module that gets Barcode and expiration date, and return coding of this info in GS1 format (read the related Wiki page).
From the encoding we will creat sticker later on.

**Comment by noamyft** [comment]
I modified the milestone because this issue is not important to the meeting of the 13.12, and i won't be able to Implement the Class until then.

**Comment by yossigil** [comment]
I have this hunch you are taking things **very slowly** @zvili  @idabran

**Comment by noamyft** [comment]
Not at all.
I just having troubles with the SQL implementation, and it took all my time.
This issue is less important, and i will do it after it.

**Comment by IdanAtias** [comment]
Can we close this issue?

**Comment by yossigil** [comment]
Probably too late, but the design pattern for this is 
```java
public interface Codex {
   String encode(String  s);
   String decode(String s);
}
```

**Comment by noamyft** [comment]
I will make the changes to fit Codex interface
