### ISSUE TITLE
Customer.registerNewCustomer(customerProfile) - get error from server

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#412]
Are there any checks that may fail this operation?

**Comment by AviadCo** [comment]
@LiorBenAmi let's debug this together, we must end the registration by the end of this week (full flow)

**Comment by LiorBenAmi** [comment]
@noamyft  can you check on the DB side of these operation.
I've got these error: 'Register new customer command failed, critical error occured from SQL Database connection'

**Comment by AviadCo** [comment]
Moved to Bugs in customer registration flow #441
