### ISSUE TITLE
Research on AI & machine learning

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#415]
Research about algorithms in Artificial Intelligence and Machine learning.
Discover way for implementing the new module (sales suggestion).

**Comment by noamyft** [comment]
I the last week (30.4-6.5) I learned algorithms and method in AI design.
Now I am trying to Implement them in our module.

**Comment by AviadCo** [comment]
@noamyft can you make WIKI on this? or send a link to read about what we will implement?
