### ISSUE TITLE
Create wiki page - High Level Design

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#42]
#40

**Comment by LiorBenAmi** [comment]
need to build design diagrams in uml

**Comment by shimonAzulay** [comment]
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Project-Directory-Layout-and-high-level-design
Added system diagram to wiki

**Comment by yossigil** [comment]
Do you use maven for these modules? Shouldn't this be documented?

**Comment by shimonAzulay** [comment]
@yossigil  Can you please guide me what should i add ? 
Should it be Maven Dependencies Diagram ?

**Comment by yossigil** [comment]
A simple list would do, if it has the exact names.

**Comment by shimonAzulay** [comment]
@yossigil  added the list. Can i close this issue?

**Comment by yossigil** [comment]
:+1:
