### ISSUE TITLE
Bugs in Ingredients and Manufacturers flow

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#424]
- [x] Remove manufacturer doesn't print error when exists.- @shimonAzulay
- [x] Add manufacturer doesn't print error when exists.- @shimonAzulay
- [x] Remove ingredient doesn't print error when exists.- @shimonAzulay
- [x] Add ingredient doesn't print error when exists.- @shimonAzulay
- [x] Critical error from SQL when trying to ADD / Remove ingredient. - @noamyft 
- [x] When removing ingredient the button of remove doesn't goes gray and the add ingredient doesn't go to normal. - @shimonAzulay 
- [x] Add button to edit existing ingredient and manufacturer. - @shimonAzulay

**Comment by shimonAzulay** [comment]
@AviadCo  please check if the problems are still occurred (i don't have Hebrew in my machine)

**Comment by AviadCo** [comment]
@shimonAzulay Hi, the bugs were fixed but i found another bug in GUI...
@noamyft please fix the SQL error with ingredient

**Comment by AviadCo** [comment]
@shimonAzulay i added another bullet on you...

**Comment by shimonAzulay** [comment]
commit : 
b7430093ce1d821e8df4a0693b279638f41969d5
