### ISSUE TITLE
Add full support to Forgot Password flow

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#425]
This issue will combine all aspects regarding to implementing this mechanism. 
**If one of the following task is already in developing in another issue, please reference this issue next to the right checkbox and mark it as done when completed.**

**Idan:**
- [x] Add 2 command APIs for handling the Forgot password mechanism.
- [x] Implement HandleForgottenPassword module. (Design & login implementation)
- [x] Support this feature in Customer (logic level. not GUI)
- [x] Support this feature in Employee (logic level. not GUI)
- [x] Add unit tests.

@AviadCo 
- [x] Implement commands in Server side.

@noamyft 
- [x] Support this commands in SQL

@shimonAzulay 
- [x] GUI support for Employee
- [x] Connect GUI to Logic
- [x] Check Flow

@LiorBenAmi 
- [x] GUI support for Customer

**Comment by shimonAzulay** [comment]
@LiorBenAmi 
I added wizard GUI for employee - i didn't finish it yet. i want to make reusable for you also with the costumer. So don't create your own Wizard.
