### ISSUE TITLE
Refactor in Costumer Exceptions 

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#433]
Each GUI exception defined in the costumer should implement: showInfoToUser()  method that is define in SMException class 
Example: InvalidParameter Exception implement  showInfoToUser() and open dialog that prints the error
``````java
public static class InvalidParameter extends AEmployeeException {

		private static final long serialVersionUID = 6423454812287539804L;
		
		@Override
		public void showInfoToUser() {
			DialogMessagesService.showErrorDialog(GuiCommonDefs.ganeralDialogTitle, null,
					GuiCommonDefs.invalidParamFailureMsg);
		}

	}
``````

Then you can use it in your code to show the error to the user:

``````java
} catch (InvalidParameter e) {
			e.showInfoToUser();
			return;
}
``````

This new refactor should replace CustomerGuiExceptionsHandler class

**Comment by LiorBenAmi** [comment]
tnx @shimonAzulay, blessed change.
Done
