### ISSUE TITLE
Investigate & Design project directories layout

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#44]
Open WIKI for the project directory layout when finish.

**Comment by yossigil** [comment]
Do you mean package structure?

**Comment by AviadCo** [comment]
done. here is the WIKI page:
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Project-Directory-Layout

**Comment by yossigil** [comment]
Ok. Seems rather minimal. It would be better if you created packages and classes. and packag-info.java files perhaps

**Comment by AviadCo** [comment]
@yossigil not just packages - we need to seperate the code to project since we want different applications to run on different device at the end...
I read a lot in the web and understood this is the best way ti implement Client - Server application

**Comment by yossigil** [comment]
So, you mean you want a multi level Maven project?

**Comment by AviadCo** [comment]
As far as i understood, the Maven sub-moudles design has 2 advantages:
1. compile all sub-projects in one command.
2. take care of the build order and dependecies for you.

The disavantage is that we need to deal with maten POM.xmls and we don't really need to compile all the projects at ones....

I'm no sure if maven sub-modules will be helpful here, but i have never used Maven before...

**Comment by yossigil** [comment]
This is the way to go. Not trivial, but that the right way to go about this

**Comment by AviadCo** [comment]
O.K. so that's how we will implement this (maven sub-module and dependencies between the projects).

10x

**Comment by yossigil** [comment]
Feel free to "borrow" from internet templates.
