### ISSUE TITLE
Bugs in customer registration flow

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#441]
GUI :
- [x] Enable only digits in the Phone field - personal info
- [x] All Gui screens - Add field required to important fields 
- [x] Disable "Next" button when required fields are empty
- [x] Personal info screen - can't see the fields names (need to change colors)
- [x] Final step screen - "back" button doesn't work after error from server occurs.
- [x] Final step screen - change terms of use to real terms

Server:

- [x] bug in 'registerCustomer' in SQLDatabaseConnection - when trying to add new customer ( @noamyft  ):

**Comment by LiorBenAmi** [comment]
@AviadCo
* about the first two bullets: the required fields need to be defined by us in the server-client api.
* terms of use: I don't think we need to define a real contract as we not selling a real product. I've chose intentionally  the [Lorem ipsum](https://en.wikipedia.org/wiki/Lorem_ipsum) to demonstrate the terms.

**Comment by shimonAzulay** [comment]
Fixed the most of them
