### ISSUE TITLE
Maven structure for the project

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#45]
The initial commit should include:

1. All the projects (modules) which mentioned in the Project directory Layout WIKI.
2. Definitions of Maven sub-modules dependencies (PRM.xml) for each sub module.

Please added a note here how to compile the project correctly in this issue or open WIKI to 'How to work with Maven sub-Modules'

10x

**Comment by yossigil** [comment]
README.MD???? Each GITHUB project has one.

**Comment by AviadCo** [comment]
You're right, changed issue to 'Commit an initialization commit for the project sub modules'

**Comment by AviadCo** [comment]
10x @yossigil

**Comment by shimonAzulay** [comment]
Separated to two issues  #52 #53

**Comment by shimonAzulay** [comment]
Done
