### ISSUE TITLE
IMPROVEMENT: when worker/manager write product package that not exist - add it

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#465]
If the worker/manager write product package that not exist (neither the shelves nor the warehouse) - the application will ask "I noticed you insert not existed package. would you like to add it to the warehouse right now?"
If no - nothing happen
If yes - than the screen change to the one that appear when you scan barcode

**Comment by shimonAzulay** [comment]
@noamyft 
Thats nice,i will check this option if there will be time.

**Comment by shimonAzulay** [comment]
Close due time schedule
