### ISSUE TITLE
User is not logged out when pressing the "door button" in Customer screen

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#471]

**Comment by IdanAtias** [comment]
@AviadCo, @noamyft - as far as I checked, i think this is caused by server side.
Before I dig even more in the client side to fix this bug, plz have a look at the server side...
Thanks!

**Comment by AviadCo** [comment]
I almost sure that the gui doesn't send logout command, @shimonAzulay can you please check this on both customer and employee?

**Comment by shimonAzulay** [comment]
@AviadCo @IdanAtias  
I checked both flows (Employee and Customer) in both of them we getting to onStageClose handle.
In worker we first check if the worker is logged in (with its API) but there is a bug in this function returning false although the worker is logged in. Therefore we are not calling logout function.
In the Customer module there isn't "is logged in" function (So we need to add it). in general we are calling logout but even if the customer is logged in there is exception that thrown that says the customer is not logged in...
