### ISSUE TITLE
Select an issue and make sure code is checked in response to that issue.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-Market#48]
So far, lots of talks and not a single line of code. This issue requires that:
- You create a maven skelton project.
- Check it in.

And, modify another issue so that it requires who completes in to check in some code.

@zvili / @idabran : I do not know the students, but you may want to assign this to one of them.
This student should add labels, e..g, first-priority and milestone.

**Comment by shimonAzulay** [comment]
@idabran @zvili  Check this closed issue #52

**Comment by AviadCo** [comment]
@idabran @zvili Check those closed issues (same commit for both):
Implement Client-Side basic Connection with server #29
Implement Server-Side basic Connection with server #32

**Comment by yossigil** [comment]
This should have been closed long ago.

@AviadCo  How is #32 relevant here?

**Comment by AviadCo** [comment]
@yossigil I misunderstood the issue, it's not relevant here.

**Comment by yossigil** [comment]
got u
