### ISSUE TITLE
Use ZenHub for better use of GitHub

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#49]
This chrome extension gives us more power in handling our project more effectively

**Comment by yossigil** [comment]
Did  you check pricing?

**Comment by IdanAtias** [comment]
Yup. It's free of charge for small groups, and also has no limitation for the number of users on public repos.

**Comment by yossigil** [comment]
Good job. If this worth it, feel free to post in facebook for others to use.
