### ISSUE TITLE
 Karma and Todos for Noam Yefet

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Market#5]
_From @noamyft on October 26, 2016 19:18_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#524_

**Comment by zvili** [comment]
_From @noamyft on October 26, 2016 19:22_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @AviadCo on October 26, 2016 20:6_

Good Job Partner, Good luck in the project
Please Give a feadback about my issue #528

**Comment by zvili** [comment]
_From @matityahuinba on October 27, 2016 11:35_

Good luck! :pray:

**Comment by zvili** [comment]
_From @nisanarz on October 27, 2016 12:34_

Great Karma page! :) 
Please check out mine #542

**Comment by zvili** [comment]
_From @AdiOmari on October 29, 2016 16:55_

Looks good 👍 , assign yourself if you haven't done so yet.

**Comment by zvili** [comment]
_From @yossigil on October 31, 2016 6:46_

edit our the blurb. leave the todos

**Comment by yossigil** [comment]
Please add here a list of all issues you worked on so far.

**Comment by noamyft** [comment]
#7 #18 #23 #24 #30 #38 #65 #83 #88

**Comment by yossigil** [comment]
💯 @AdiOmari
