### ISSUE TITLE
Add full support to search & display products locations in Customer

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#526]
@IdanAtias
- [x] Add command API for fetching the whole Catalog from Server
- [x] Add implementation to Customer class
- [x] Implement GUI logic for Customer screen

@shimonAzulay 
- [x] GUI

@AviadCo 
- [x] Implement command on Server

@noamyft 
- [x] Add support in DB

**Comment by shimonAzulay** [comment]
Done
