### ISSUE TITLE
Please give me write access to wiki

### ISSUE THREAD

**Issue by OriRoth** [TechnionYP5777/SmartCity-Market#545]
And answer my questions there.

**Comment by kapalex** [comment]
I need as well

**Comment by OriRoth** [comment]
Go to Settings -> Collaborators and teams -> add collaborator.

**Comment by OriRoth** [comment]
Ahm

**Comment by kapalex** [comment]
Also is there some instance of the server I can connect to without installing? 
The installation is very long and I just need to use it as a client, not a developer

**Comment by AviadCo** [comment]
@OriRoth - i gave access write to the project to the following people:
@matityahuinba 
@mdoron
@KaplanAlexander 
@OriRoth 
@michalcohen 

anyone else?

**Comment by AviadCo** [comment]
@KaplanAlexander - we  tried to make a running jar files but we had problems with that, for now we have only a developer guide option.
