### ISSUE TITLE
[Final] - Using the scanner for Iphone users?

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-Market#547]
Hi,

What do iPhone lovers do when installing the scanner app?

**Comment by AviadCo** [comment]
We support only Android for scanner... can you ask form a friend an android smartpone?

**Comment by matityahuinba** [comment]
The whole group with iPhones :(
Problematic choice..
You have an available device?

**Comment by IdanAtias** [comment]
even if we had one available, we cant meet according to the "game"'s rules.

**Comment by AviadCo** [comment]
The scanner is just for convey the idea of scanning barcode.... the main goal is to use real barcode scanner....
Iphone won't be supported - Sorry :)
