### ISSUE TITLE
What username should I use for customer?

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/SmartCity-Market#548]
I remember you have only one employee so what is the username and pass?

**Comment by IdanAtias** [comment]
one options is to enter as guest in the Customer application.
Second options is to do the the registeration flow and create another user & pass

**Comment by tanyabrokhman** [comment]
no. employee not customer. no way to register as new employee

**Comment by shimonAzulay** [comment]
If you want to add a new employee you should enter the Employee login screen with: user: admin pass: admin. Then enter the manage employee tab to add new employee .

**Comment by tanyabrokhman** [comment]
ok. 10x
