### ISSUE TITLE
[Final] - No apache?

### ISSUE THREAD

**Issue by OriRoth** [TechnionYP5777/SmartCity-Market#549]
The project refuses to compile.
![wow](https://user-images.githubusercontent.com/15183108/27769084-82994dce-5f2a-11e7-8daa-00ba46d9af0a.jpg)

**Comment by OriRoth** [comment]
Also no `com.google.inject`... seems the pom does not work.

**Comment by AviadCo** [comment]
Can you please run maven update on the main project? (SmartMarket)

**Comment by OriRoth** [comment]
I did.

**Comment by AviadCo** [comment]
Did you follow all steps of the WIKI installation?

**Comment by OriRoth** [comment]
Kind of? It is very specific though, only a Maven issue.

**Comment by AviadCo** [comment]
Sorry for late respond - we have never had this compilation error... Can you running 'mvn test' on tommorow time, maybe it will shed some light why maven doesn't download the apache library for you.

**Comment by AviadCo** [comment]
@OriRoth are still checking our project to give us more info?

**Comment by OriRoth** [comment]
I am now trying to install the project in Linux

**Comment by OriRoth** [comment]
Works :)
