### ISSUE TITLE
[Final] - Trouble getting installed

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-Market#550]
Install me asks for -

![image](https://user-images.githubusercontent.com/15820085/27769074-46bc9720-5f2a-11e7-8068-7a6b956afddc.png)

Where I can find "ServerRunner.Main"?

![image](https://user-images.githubusercontent.com/15820085/27769053-0d04b738-5f2a-11e7-9e2e-008fdf4d9501.png)

**Comment by noamyft** [comment]
Its under "Server" Project
In package: ServerRunner

**Comment by matityahuinba** [comment]
![image](https://user-images.githubusercontent.com/15820085/27769161-6db81c80-5f2c-11e7-87e0-8f4a0a958f04.png)

like this?

**Comment by noamyft** [comment]
like this: 
![screenshot from 2017-07-02 13-47-37](https://user-images.githubusercontent.com/18020768/27769195-5f1b9868-5f2d-11e7-9142-1fc43baee3ba.png)

**Comment by matityahuinba** [comment]
I wrote manually, hope it will work..
