### ISSUE TITLE
[Final] - When trying to make a smartcode as an admin nothing happens

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Market#551]
The flow :
1. Run Server
2. Run employee
3. login as admin
4. enter number in barcode
5. Choose date (it just says date, is it expiration or creation?)
6. ??

Nothing happens after I choose a date

**Comment by shimonAzulay** [comment]
SmartCode combined from barcode and expiration date.
So if the above is not in the system we will not be able to find it.
First add product package with expired date 
And then you could add the date like you did.

**Comment by kapalex** [comment]
There should be some indication that is the case, I don't get any error, just _nothing_

**Comment by AviadCo** [comment]
Indication of what? there is a log in the bottom of the screen, furtheremore there is a notification for errors.
what is the specific error you found?

**Comment by AviadCo** [comment]
We made some fixes, can you please check again?

**Comment by shimonAzulay** [comment]
Check the user guide
