### ISSUE TITLE
On smaller screens the "add product" button is not available

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Market#553]
When I first entered the "manage catalog products" there was no "Add product" button, had to put it full screen to see it

**Comment by shimonAzulay** [comment]
What is your screen size?

**Comment by kapalex** [comment]
I'm in the SSDL (their comps) resolution is 1280x1024

**Comment by shimonAzulay** [comment]
Can you change the resolution to 1920 X1080  ? we tested the app on this res

**Comment by kapalex** [comment]
The screen here doesn't support it sadly
either way a scroll bar should be there for when the screen is too small

**Comment by AviadCo** [comment]
I agree with you that a scroll bar would be nice but JavaFX wasn't very kind with us when we tried to support multiple resolutions. We focused on 1920 X1080 for now (asked the stuff permission to not spend a lot of time on GUI games).
