### ISSUE TITLE
Where can I find some smart codes for the app to scan?

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/SmartCity-Market#554]

**Comment by AviadCo** [comment]
@mdoron  - when adding new package, you have an option to print the Smartcode - print it to PDF file and  then you will have a smartcode. o.k?

**Comment by mdoron** [comment]
As an employee or as a costumer?

**Comment by AviadCo** [comment]
as employee (both Manager and Worker can do the operation)

**Comment by noamyft** [comment]
You also can write it manually. like that:
![scan product](https://user-images.githubusercontent.com/18020768/27769357-75d2545e-5f30-11e7-9246-f8464c234371.png)

And i can give you already printed smartcode

**Comment by noamyft** [comment]
try also this:
![photo_2017-07-02_14-27-56](https://user-images.githubusercontent.com/18020768/27769476-b6ac6c4c-5f32-11e7-80d0-3081c4fba355.jpg)
