### ISSUE TITLE
[Final] - some windows remain opened

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/SmartCity-Market#555]
what I did:
1. tried to restore pass in login screen. Got the window to enter username answer question and add new pass. Gave wrong answer on purpose. Got an error msg in a new window. 
2. entered correct user and pass and loged in
3. the window that asked for security question and new pass is still open for the user I tried to restore the pass for

**Comment by AviadCo** [comment]
@tanyabrokhman please try to run the same scenario on the lastest version (run git pull).
i followed the same scenario andit seems that there is no problem there...
