### ISSUE TITLE
adding new manufacturer

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/SmartCity-Market#557]
1. added new manufacturer - tanya
2. pressed done
3. pressed "add manufacturer" again.
4. the input field still had the value I already entered. It should be cleaned out

**Comment by shimonAzulay** [comment]
@tanyabrokhman  i am checking

**Comment by shimonAzulay** [comment]
@tanyabrokhman  we checked on two computers and the field is cleared
