### ISSUE TITLE
Exception when runnin Customer

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/SmartCity-Market#558]
![image](https://user-images.githubusercontent.com/11704810/27769212-e30db46c-5f2d-11e7-9352-f81c0abee5b5.png)

Ran using -i 127.0.0.1 -p 2000 -v true after running server and employee

**Comment by AviadCo** [comment]
Hi,
did you run both customer and employee at the same time?

**Comment by michalcohen** [comment]
First the server, then the employee (it worked) and only then the customer.
If I try to open eclipse in several different instances, it refuses due to workspace issues
@AviadCo

**Comment by AviadCo** [comment]
Did you close the employee project before running the Customer project?
JavaFX doesn't support both of them to run at once.

**Comment by michalcohen** [comment]
Working! Looks greate! @AviadCo
