### ISSUE TITLE
failed to add new product

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/SmartCity-Market#560]
![image](https://user-images.githubusercontent.com/25345526/27769251-b4eb2a3c-5f2e-11e7-9e13-b78c3817f326.png)
![screenshot from 2017-07-02 13-59-14](https://user-images.githubusercontent.com/25345526/27769256-c4471cf2-5f2e-11e7-8781-f98a75924b9b.png)

**Comment by IdanAtias** [comment]
@tanyabrokhman it seems like you are not using the most recent version of our project.
Plz re-clone our repo, or at least do git fetch & git pull.
afterward refresh your IDE environment.
tnx
