### ISSUE TITLE
Can't do anything from the customer page?

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Market#561]
This might just be me confused but

I created a new user and logged in
I type a name of a product and click on the
The information for the product is shown, what now?

Show location does nothing
I don't see an option to add to card
It says "Amount in the grocery list" is "N/A"

Am I missing something?

**Comment by LiorBenAmi** [comment]
the main flow of the customer screen is to scan smartcode of product and add it to the cart.
in the search product you get all the products in the market.
try type: "ב" and see what you get.
