### ISSUE TITLE
show stopper: how can I test your app without the nothing to scan?

### ISSUE THREAD

**Issue by tanyabrokhman** [TechnionYP5777/SmartCity-Market#565]
this is a show stopper. you should have provided a user manual with detailed instructions how to use your application for 3 types of users:
1. manager
2. employee
3. customer

and you SHOULD have provided a list of codes to scan or an alternative way to add products. For example: I can't even shop as a customer

@TomPalny FYI

**Comment by IdanAtias** [comment]
![image](https://user-images.githubusercontent.com/12379320/27769409-44c95618-5f31-11e7-8a59-17428c5f90b4.png)
