### ISSUE TITLE
[Final] - Error - CustomerApplicationScreen could not find or load

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-Market#566]
During the installation process, I encountered this error, why? :( 

![image](https://user-images.githubusercontent.com/15820085/27769362-9a303e60-5f30-11e7-99dd-2d625fbec668.png)

**Comment by AviadCo** [comment]
Can you please add screenshot of the run confiugration screen?

**Comment by matityahuinba** [comment]
A spelling error was found in Install Me - CustomerGuiScreen.CustomerApplicationScreen instead of 
CustomerGuiScreens.CustomerApplicationScreen
After going through your file folders I realized..

**Comment by AviadCo** [comment]
Ohh really sorry - i will update it now.

**Comment by AviadCo** [comment]
Wiki was updated.
