### ISSUE TITLE
[Final] - Run configuration of customer

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/SmartCity-Market#567]
Got
`Error: Could not find or load main class CustomerGuiScreen.CustomerApplicationScreen
`

Change in the install me to CustomerGuiScreens.CustomerApplicationScreen

**Comment by AviadCo** [comment]
Now i understood you - Wiki was update (There was type mistake)

**Comment by AviadCo** [comment]
@mdoron ?
