### ISSUE TITLE
FOR ALL TESTERS

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#571]
We changed the database

Please do git pull before using the app

Also, we added Wiki that explains how to use

[here](https://github.com/TechnionYP5777/SmartCity-Market/wiki/User-Guide)

**Comment by michalcohen** [comment]
The link is broken (redirect to this page)

**Comment by noamyft** [comment]
fixed. thanks.

**Comment by AviadCo** [comment]
@michalcohen @mdoron @matityahuinba @OriRoth @KaplanAlexander -

When we will add new bug fixes we will notify you here, and then run from your main repository:
git stash (to put all database changes aside)
git pull

**Comment by IdanAtias** [comment]
**In addition, after doing git pull, stop the server and whatever other application that's running (Employee, Customer) and start it again for changes to take effect.**

**Comment by OriRoth** [comment]
So... I still need to import the project?

**Comment by IdanAtias** [comment]
if you have not done this already then yes.

**Comment by michalcohen** [comment]
Is there a way to "scan" products in order to simulate the customer side?

**Comment by IdanAtias** [comment]
No, you must scan the products. 
This is on purpose for avoiding corruption of our DB.
(This is of course applies to the real world situation of buying in a real market. 
A nice to have feature would be to support this in Debug mode, so you can "scan" the products, but we had more urgent things to do)

**Comment by michalcohen** [comment]
What is the name of the wiki explaning how to scan?

**Comment by LiorBenAmi** [comment]
please pull for new bug fixed

**Comment by noamyft** [comment]
Thank you all!!
Good Luck!
