### ISSUE TITLE
Registration - Invalid fields

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-Market#573]
When registering - there no limit on the fields type?
Can you enter a private first and last name as numbers?
Can I answer the question as numbers?

![image](https://user-images.githubusercontent.com/15820085/27788678-3a0227e8-5ff2-11e7-99a2-0f8098029178.png)

Registration success..

**Comment by LiorBenAmi** [comment]
Yes it is possible. we don't limits person name. no judgment ;)
