### ISSUE TITLE
Insert product to groceries list

### ISSUE THREAD

**Issue by matityahuinba** [TechnionYP5777/SmartCity-Market#579]
How do I enter the product to list of groceries?
![image](https://user-images.githubusercontent.com/15820085/27789504-9a2c4510-5ff5-11e7-99bf-bb5bd9024b03.png)

in the user manual there are two buttons that doesnt appear..
![image](https://user-images.githubusercontent.com/15820085/27789616-e3051956-5ff5-11e7-9c24-a8ec9cb840f5.png)

what did I do wrong? :(

**Comment by IdanAtias** [comment]
this is because you are in "Search mode" (because of that little 'a' that is written at the top).
Clear the search, and SCAN a smartcode for adding the product.
(You need to really scan the smartcode for doing this )
The scanning application is available from our InstallMe wiki

**Comment by matityahuinba** [comment]
Got it! Thanks!
