### ISSUE TITLE
Add parallel tests to server communication

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#58]
Add test which checks server to many clients conncetion

**Comment by yossigil** [comment]
Huge can of worms

**Comment by AviadCo** [comment]
I agree, but still must be done :) @yossigil

**Comment by yossigil** [comment]
Or borrowed

**Comment by IdanAtias** [comment]
@AviadCo I believe you already added these test so I close this.
reopen if i am wrong

**Comment by AviadCo** [comment]
@IdanAtias not yet my friend....

**Comment by AviadCo** [comment]
No time to get into this..
