### ISSUE TITLE
Image in java

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#59]
learn and activate the use of image in CatalogProduct.
#27

**Comment by yossigil** [comment]
Issue title is better phrased "implement demo of X using Y".

@idabran @zvili

**Comment by LiorBenAmi** [comment]
Chose:
BufferedImage. with using of ImagIO and URL classes
based on: [Working with Images - Java Tuturial](https://docs.oracle.com/javase/tutorial/2d/images/index.html)
