### ISSUE TITLE
Karma and Todos for Shimon Azulay

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Market#6]
_From @shimonAzulay on November 3, 2016 6:59_

- [x]  Make sure you present yourself by a readable nick
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job
- [x]  Connect to the host repo

_Copied from original issue: SpartanRefactoring/Spartanizer#759_

**Comment by zvili** [comment]
_From @shimonAzulay on November 3, 2016 7:1_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @IdanAtias on November 14, 2016 17:56_

the best karma page ive ever seen in my life

**Comment by zvili** [comment]
_From @shimonAzulay on November 14, 2016 17:57_

@IdanAtias  ya halalau

**Comment by shimonAzulay** [comment]
Adding my progress in the project:
First i was charged for reading about JSON and client - server implementation in Java and how to use it.
After reading about it i started building WIKI page for the mentioned above but didn't finish yet.
Now i responsible on #28 #33 #42 #45.
Also i responsible on #15 #16 #36 #35 but all those issues are need to be edited probably due to comments i got from the project stuff.

**Comment by yossigil** [comment]
Please clean the above, mentioning only issues you closed, or did some observable work on. If you did some work without issues documenting you may in some cases create the issues retroactively, in some cases though, this is impossible.

**Comment by shimonAzulay** [comment]
Updating summary of the work i contribute to the project.
**Client side:**
-Design and implement BL to Employee - Worker and Manager.
-Create Unit tests for the client side BL Employee Worker.
-Design and implement the GUI for the client side Employee - Worker and Manager.
**Common:**
-Added the basic maven project.
-Added infrastructure for using Dependency Injection in the project with Guice.
-Added Mockito framework to the project for Unit tests.
-Added Event Bus framework to the project for communicate between GUI components.
**Wiki:**
-Added Wiki about maven.
-Added Wiki about Dependency injection.
-Added Wiki about unit testing with mockito and DI.
-Added Wiki about our project design.

**Comment by yossigil** [comment]
💯
