### ISSUE TITLE
Create WiKi page about maven and how to use it in our project

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#63]

**Comment by yossigil** [comment]
:+1:

**Comment by shimonAzulay** [comment]
Done

**Comment by shimonAzulay** [comment]
Reopen due to continues wiki build. For now the wiki that i built serves our needs but in the future more information will be added.

**Comment by yossigil** [comment]
When would this be closed. Did you do it?

**Comment by shimonAzulay** [comment]
Yep :)

**Comment by yossigil** [comment]
Please add a link to the wiki

**Comment by shimonAzulay** [comment]
[Maven Wiki Page](https://github.com/TechnionYP5777/SmartCity-Market/wiki/Maven-Project)

**Comment by yossigil** [comment]
Thanks
