### ISSUE TITLE
Write Wiki about HSQLDB

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#64]
as mentioned in #31.

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
And, where is the wiki?

**Comment by noamyft** [comment]
Maybe i forgot to mention here, but the wiki is in the "Wikis" section.
(link: https://github.com/TechnionYP5777/SmartCity-Market/wiki/HSQLDB)
