### ISSUE TITLE
Decide which library to use for parsing and generating JSON

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartCity-Market#65]
Its relevant for all of us, but particularly for @LiorBenAmi.
We need to decide which library is better for us: GSON or JACKSON or something else.
Its not really matter, but if lior familiar with one of them - i guess we should choose it.

**Comment by yossigil** [comment]
I believe other groups on smart city were engaged in similar discussion. You may want to dig there, post in facebook, blow a chanting whistle, or simply ignore

**Comment by LiorBenAmi** [comment]
Chose GSON for now. The using of it for client-server side is amazingly simple. 
I'll add an explanation to the relevant wiki.
For the SQL DB -> Server: We may want other module. More check need to be done at that side.
Therefore need to remain this issue open for now.

**Comment by LiorBenAmi** [comment]
The wiki: https://github.com/TechnionYP5777/SmartCity-Market/wiki/JSON-For-Client-Server-Data-Exchange

**Comment by yossigil** [comment]
Good job Lior #12. Keep this updated when you resolved the missing details

**Comment by noamyft** [comment]
We dont need other modules. you can create JSON with jsonWriter (or just concatinating strings) and you can parse JSON with JsonParser
I will updated the missing details soon.
