### ISSUE TITLE
Add basic structure for Login

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#77]
this structure will be used in Login commands.
Before any client want to request stuff from the server he must login using username & password.
The client will sent a **Login** structure in the command data and will get respond for operation status. only after a successful login, the client is allowed to send other commands.

**Comment by yossigil** [comment]
Hi @AviadCo , just interested? What does issue mean? I could delve in the commit, but it would be nice if it was clear from the issue.

**Comment by AviadCo** [comment]
Hi @yossigil , i updated the descreption to understand the need and use of Login structure.

**Comment by yossigil** [comment]
Yuck. It is basically session management... Look for the term, and see if you can borrow instead of building this
