### ISSUE TITLE
Write user stories for server

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#8]
Write all relevant user stories for system.

**Comment by shimonAzulay** [comment]
@AviadCo  Done.

**Comment by yossigil** [comment]
Not sure what you mean by user stories, but these do not look like stories to me.

A story is, e.g., : User X, interested in a product Y thinks it is too expensive, and conducts a seach for mocks of Y.

@idabran @zvili

**Comment by AviadCo** [comment]
I changed the 'system' to 'server' and changed the style of the user story, is that good?

@idabran @zvili

**Comment by shimonAzulay** [comment]
@AviadCo Thanks for the change

**Comment by AviadCo** [comment]
We will create issues to implement the server side as sub-issues. 
This issue is ignored.
