### ISSUE TITLE
Integrate Mockito to our project & Investigate how to use "Mocking" in our unit-testing

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Market#84]

**Comment by IdanAtias** [comment]
Use Mockito for our unit testing.
http://site.mockito.org/

**Comment by shimonAzulay** [comment]
We need to search how to do unit testing without dependency injection.
Or consider to use DI.

**Comment by IdanAtias** [comment]
All we need is here:
https://www.youtube.com/watch?v=DJDBl0vURD4

**Comment by shimonAzulay** [comment]
After we close this issue, handle the issue #81

**Comment by yossigil** [comment]
Better phrase.

**Comment by shimonAzulay** [comment]
I integrated it to our project added wiki about it 
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Dependency-Injection-and-Unit-Testing-With-Mockito
