### ISSUE TITLE
Add Server SQLDatabase Logger

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#86]
This commit should include:
1. Logger initialization in the SQLDatabase (see example in ThreadPooledServer).
2. Logger important prints.
3. Implement TODO on ServerMain.java

**Comment by yossigil** [comment]
When do you expect this issue to close?

**Comment by AviadCo** [comment]
@yossigil We already add some log prints to the SQL.

1 & 3 are done, need only to do 2 - Logger important prints.

The SQL is still in developement, we add prints on the fly. this is issue should be closed with the implementation on the SQL (about end of the next week 14.1)

@noamyft Am I right?

**Comment by yossigil** [comment]
ok

**Comment by noamyft** [comment]
I left it opened until now because i did changes all the time.

**Comment by yossigil** [comment]
👍
