### ISSUE TITLE
Gui - decide on gui module for the app; Implement  Basic window for worker Login and GetProduct

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#87]
## Modules Possibilities 
* JavaFX
* Swing
* Awt

**Comment by LiorBenAmi** [comment]
#28

**Comment by LiorBenAmi** [comment]
[JavaFx Overview](http://docs.oracle.com/javase/8/javafx/get-started-tutorial/jfx-overview.htm#BABDJEFB)

**Comment by LiorBenAmi** [comment]
## Download JavaFX Scene Builder 
The file can't find in [the official Oracle JavaSE Downloads](http://www.oracle.com/technetwork/java/javase/downloads/index.html) anymore. 
I downloaded it from http://gluonhq.com/labs/scene-builder/#download

**Comment by shimonAzulay** [comment]
Add SWT also to the options

**Comment by yossigil** [comment]
JAVAFx seems to be the reasonable decision, since local expertise was gained.

**Comment by LiorBenAmi** [comment]
Tnx, after trying all those modules we indeed chose JavaFX.  Although we still experience learning - compilation and using challenges

**Comment by shimonAzulay** [comment]
@LiorBenAmi  i assign myself to this issue. i will start to implement the GUI.

**Comment by shimonAzulay** [comment]
Ok we decided to go with JavaFX and i started to implement the GUI. So i close this issue

**Comment by yossigil** [comment]
:+1:
