### ISSUE TITLE
Investigate dependency injection

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#90]
Dependency injection can contribute to unit tests.
Investigate DI and its advantages.

**Comment by yossigil** [comment]
Make this more definite, e.g., "trial jmplementation of di in class X', if this task fails, then the issue is also done.

**Comment by shimonAzulay** [comment]
@LiorBenAmi @AviadCo @IdanAtias @noamyft 
I added wiki about this subject, please check it out 
https://github.com/TechnionYP5777/SmartCity-Market/wiki/Dependency-Injection-and-Unit-Testing-With-Mockito

**Comment by yossigil** [comment]
:+1:
