### ISSUE TITLE
Apply the spartanizer plugin

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-Market#95]
The guidlines where that the spartanizer plugin should be used, and no tipping should be made.

@zvili @idabran: FYI.

**Comment by AviadCo** [comment]
Done.

Currently, there are no spartinizer issues.
Sometimes the Spartinizer dosen't alert when running laconize but we mantain that when seeing tips we fix them ASAP

**Comment by yossigil** [comment]
Fill free to open issues as necessary.

**Comment by AviadCo** [comment]
Next time such thing happens on Spartinizer we will open an issue  for that.
