### ISSUE TITLE
Code refactor: remove redundant code from c'tor

### ISSUE THREAD

**Issue by AviadCo** [TechnionYP5777/SmartCity-Market#96]
There is no reason to initialize fields to their default value in the c'tor

**Comment by yossigil** [comment]
:+1:

**Comment by AviadCo** [comment]
@shimonAzulay please refactor code in Employee project and make a commit fix if need (update me anyway so i can close this issue).

10x

**Comment by AviadCo** [comment]
@shimonAzulay As far as i found, there are no redundant code in the Employee C'tors, issue closed.
