### ISSUE TITLE
Refactor in Server module 

### ISSUE THREAD

**Issue by shimonAzulay** [TechnionYP5777/SmartCity-Market#98]
Change the direct use of Gson to use The Serialization that in Utils

**Comment by shimonAzulay** [comment]
@AviadCo Did you handle this ?

**Comment by AviadCo** [comment]
@shimonAzulay i will do the code refactoring after we will finish the Employee-Cart-Server comuunication.

**Comment by AviadCo** [comment]
@noamyft Noam - please refactor in SQLConnection class.
thanks

**Comment by noamyft** [comment]
@shimonAzulay 
Why to use the Serialization that in Utils instead of Gson?
In addition, the name "Serialization" is confusing because it has another meaning in java
